### ISSUE TITLE
[Bug]: Empty Scans

### ISSUE THREAD

**Issue by Poisonenvy2** [nikkisaurus/GuildBankSnapshots#12] opened 2022-12-19 23:55 UTC
### Interface Version

10.0.2

### AddOn Version

3.4.5

### Have you replicated this error without any other addons loaded?

No.  Not tried .. but can do if needed.

### What steps did you take leading up to this issue?

Open guild vault.   I have tried to adjust the delay to the maximum, thinking it might just be related to lag, but it didn't make any difference.

Scans occasionally work, but most of the time the results have an almost blank page, with no tab headings for the guild vault, or it has the tab headings but no content.  At the very least there should be gold updates relating to repairs.

*Edit - just realised my first screenshot isn't really big enough .. essentially the rest of the page is blank .. no tabs or anything else.  Can provide a better pic if needed.

LUA error (only error, current session):

45x GuildBankSnapshots/Modules/Helpers.lua:58: bad argument #1 to 'strfind' (string expected, got nil)
[string "=[C]"]: in function `strfind'
[string "@GuildBankSnapshots/Modules/Helpers.lua"]:58: in function <GuildBankSnapshots/Modules/Helpers.lua:56>
[string "=[C]"]: in function `sort'
[string "@GuildBankSnapshots/Libs/LibAddonUtils/LibAddonUtils.lua"]:129: in function `pairs'
[string "@GuildBankSnapshots/Modules/Helpers.lua"]:56: in function `GetFilterItems'
[string "@GuildBankSnapshots/Modules/Review.lua"]:114: in function <GuildBankSnapshots/Modules/Review.lua:100>
[string "@GuildBankSnapshots/Modules/Review.lua"]:213: in function <GuildBankSnapshots/Modules/Review.lua:208>
[string "=[C]"]: ?
[string "@Altoholic/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...faceAltoholic/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Altoholic/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Altoholic/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@GuildBankSnapshots/Modules/Review.lua"]:232: in function <GuildBankSnapshots/Modules/Review.lua:219>
...
[string "@Altoholic/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...faceAltoholic/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Altoholic/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Altoholic/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@GuildBankSnapshots/Modules/Frame.lua"]:47: in function <GuildBankSnapshots/Modules/Frame.lua:46>
[string "@Decursive/Libs/AceHook-3.0-9/AceHook-3.0.lua"]:92: in function <...ceDecursive/Libs/AceHook-3.0/AceHook-3.0.lua:87>
[string "=[C]"]: in function `Show'
[string "@Altoholic/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-Frame.lua"]:129: in function `Show'
[string "@GuildBankSnapshots/Modules/Frame.lua"]:58: in function `LoadFrame'
[string "@GuildBankSnapshots/Modules/Scan.lua"]:66: in function <GuildBankSnapshots/Modules/Scan.lua:7>
[string "@GuildBankSnapshots/Modules/Scan.lua"]:187: in function <GuildBankSnapshots/Modules/Scan.lua:153>

### Please supply any screenshots relevant to this issue.

![image](https://user-images.githubusercontent.com/104738891/208549515-1f4c2824-bc9f-4a1c-97d1-d8e7d258d3ca.png)
![image](https://user-images.githubusercontent.com/104738891/208549552-27cfbab1-27cb-41a6-8aab-bcf9474dec7e.png)
![image](https://user-images.githubusercontent.com/104738891/208549668-7f731f7d-177c-419d-a716-b681d12b03d8.png)

### Please supply a copy of your saved variables.

Note it wouldn't allow me to attach lua file, hopefully this works.

[GuildBankSnapshots.txt](https://github.com/nikkisaurus/GuildBankSnapshots/files/10263562/GuildBankSnapshots.txt)

**Comment by nikkisaurus** [comment] 2022-12-30 12:33
I haven't been able to find a way to clear corrupted scans automatically that are empty because I haven't thought of a good way to differentiate between a new guild bank with no transactions and a corrupt scan with missing transactions. However, I did add a cleanup for scans that had invalid items, which was what caused your lua error and subsequently the incomplete GUI.

As far as the empty scans, I've added an additional step to help ensure all the data is available at the time of the scan. I believe the issue is usually upon your first login when you first open the bank. I've added a query for each individual transaction before the scan begins to save data to basically cache the info.
I've tested it several times by logging completely out of the game, logging in and scanning. Before this change, I was getting incomplete scans with missing itemLinks (which caused the error above). After, I haven't had an incomplete scan.
I'm not sure if this will solve the issue of completely empty scans, but in theory it should, because an incomplete scan would come from the data not being available at the time the transaction is queried.

This update has been released as a [beta](https://github.com/nikkisaurus/GuildBankSnapshots/releases/tag/v3.5.0-beta1), pending your response. Let me know if this fixes your issue or if you have more problems. Thanks!

**Comment by Poisonenvy2** [comment] 2022-12-31 00:11
Thank you .. I've downloaded and will check next time I log in, and let you know ;-)

**Comment by Poisonenvy2** [comment] 2023-01-02 00:04
Sorry .. been very distracted over the last few days!  That seems to work great, thank you ;-)  I've also gone back through and deleted any "empty" scans, just in case they were likely to cause issues in the future.  Of course what I should have done was checked the clean-up option .. too late now :P

**Closed as completed** 2023-02-02 10:40 UTC
Labels: bug
